# Generated by Django 5.1.4 on 2024-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essential", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="media/books/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.PositiveIntegerField(default=1, max_length=6),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="audio",
            field=models.FileField(upload_to="media/vocab/audio/"),
        ),
    ]
