# Generated by Django 5.1.4 on 2024-12-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essential", "0002_alter_book_image_alter_book_level_alter_vocab_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="level",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
