# Generated by Django 5.1.4 on 2024-12-08 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essential", "0005_alter_unit_unit_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_num",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ]
            ),
        ),
    ]
