# Generated by Django 5.1.4 on 2024-12-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("essential", "0006_alter_unit_unit_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vocab",
            name="en",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
